# Generated by Django 5.0.1 on 2024-01-23 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biographie_band_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='biographie',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock'), ('GP', 'Gospel')], default='GP', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2004, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
