# Generated by Django 5.0.1 on 2024-01-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='like_new',
            field=models.CharField(max_length=29, null=True),
        ),
    ]
